#! /bin/sh
node index sounds/dolphin_panda.wav
node index sounds/emptybliss01.wav
node index sounds/hearingcrop.wav
node index sounds/hopelana.wav
node index sounds/innerkelly.wav
node index sounds/julien_crop.wav
node index sounds/overlord.wav
node index sounds/phatom_crop.wav
node index sounds/brokenhearted_tim.wav
node index sounds/crime_pays_gibbs.wav
node index sounds/crumb_plants.wav
node index sounds/deleteforever.wav
node index sounds/pigeons.wav
node index sounds/summer.wav
node index sounds/theif_contact2.wav
