#! /bin/bash
INSTALL_DIR=Yaafe/build/install
export PATH=$PATH:$INSTALL_DIR/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INSTALL_DIR/lib
export PYTHONPATH=$PYTHONPATH:$INSTALL_DIR/lib/python3.9/site-packages
python src_py/script.py
